# Generated by Django 3.0.3 on 2020-11-18 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_usertoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 18, 16, 47, 43, 543536), null=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 18, 16, 47, 43, 543536), null=True),
        ),
    ]
