# Generated by Django 3.0.3 on 2020-11-18 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201118_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 18, 19, 34, 43, 672016), null=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 18, 19, 34, 43, 672016), null=True),
        ),
    ]
