# Generated by Django 3.0.3 on 2020-11-18 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201118_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 18, 20, 22, 18, 884686), null=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 18, 20, 22, 18, 884686), null=True),
        ),
    ]
