# Generated by Django 3.0.3 on 2020-11-19 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20201118_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 19, 17, 7, 8, 16036), null=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 19, 17, 7, 8, 16036), null=True),
        ),
    ]
