SECRET_KEY = 'pf^xo)*v!!e!$1u#g1%#43gz^m6ied^ec_&()hr#^=vwyxj$kx'
STATE = "State"
SUCCESS = "Success"
FAILED = "Failed"
TOKEN = "Token"
MESSAGE = "Message"
LOGIN_SUCCESSFULLY = "Login successfully"
CREATED_SUCCESSFULLY = "User created successfully"
ALREADY_EXISTS = "User already exists"
LOGIN_FAILED = "Login failed"
EXCEPTION = "Exception"
INVALID_CREDENTIAL = "Invalid credential"
