# Generated by Django 3.0.3 on 2020-11-18 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 18, 16, 47, 43, 529570), null=True),
        ),
    ]
