# Generated by Django 3.0.3 on 2020-11-19 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20201118_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 19, 17, 7, 8, 6063), null=True),
        ),
    ]
